# hostapd_wlan3.conf
interface=wlan3
driver=nl80211
ssid=VirtualBox_ubuntu_6GHz
hw_mode=a
channel=5
# 6GHz 專屬設定
# ieee80211ax=1
# he_oper_centr_freq_seg0_idx=7
# op_class=131
# 6GHz 必須使用 WPA3
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
ieee80211w=2
wpa_passphrase=0987654321
